-- apply changes
create table dincantation (
  id                            integer generated by default as identity not null,
  name                          varchar(255),
  constraint uq_dincantation_name unique (name),
  constraint pk_dincantation primary key (id)
);

create table dspell (
  id                            integer generated by default as identity not null,
  name                          varchar(255),
  constraint uq_dspell_name unique (name),
  constraint pk_dspell primary key (id)
);

create table dspell_dincantation (
  dspell_id                     integer not null,
  dincantation_id               integer not null,
  constraint pk_dspell_dincantation primary key (dspell_id,dincantation_id)
);

create index ix_dspell_dincantation_dspell on dspell_dincantation (dspell_id);
alter table dspell_dincantation add constraint fk_dspell_dincantation_dspell foreign key (dspell_id) references dspell (id) on delete restrict on update restrict;

create index ix_dspell_dincantation_dincantation on dspell_dincantation (dincantation_id);
alter table dspell_dincantation add constraint fk_dspell_dincantation_dincantation foreign key (dincantation_id) references dincantation (id) on delete restrict on update restrict;

